import http from './index'

export const listStudentCases = (params = {}) => http.get('/student-cases', { params })
export const listCaseCycles = () => http.get('/student-cases/cycles')
export const createCaseCycle = (data) => http.post('/student-cases/cycles', data)
export const createStudentCase = (data) => http.post('/student-cases', data)
export const getStudentCase = (id) => http.get(`/student-cases/${id}`)
export const getFamilyCases = () => http.get('/student-cases/children')
export const getCaseProgress = (params = {}) => http.get('/student-cases/progress', { params })
export const updateStudentCase = (id, data) => http.patch(`/student-cases/${id}`, data)
export const updateStudentProfile = (id, data) => http.put(`/student-cases/${id}/student-profile`, data)
export const transitionStudentCase = (id, data) => http.post(`/student-cases/${id}/transition`, data)
export const createCaseReview = (caseId, data) => http.post(`/student-cases/${caseId}/reviews`, data)
export const decideDeyuReview = (caseId, data) => http.post(`/student-cases/${caseId}/deyu-review`, data)
export const exportStudentCase = (id) => http.get(`/student-cases/${id}/export`, { responseType: 'blob' })
export const upsertSubjectPlan = (caseId, subject, data) => http.put(`/student-cases/${caseId}/subject-plans/${encodeURIComponent(subject)}`, data)
export const listSubjectSuggestions = (caseId) => http.get(`/student-cases/${caseId}/subject-suggestions`)
export const createSubjectSuggestion = (caseId, data) => http.post(`/student-cases/${caseId}/subject-suggestions`, data)
export const createCaseTask = (caseId, data) => http.post(`/student-cases/${caseId}/tasks`, data)
export const updateCaseTask = (caseId, taskId, data) => http.put(`/student-cases/${caseId}/tasks/${taskId}`, data)
export const requestTaskChange = (caseId, taskId, data) => http.post(`/student-cases/${caseId}/tasks/${taskId}/change-request`, data)
export const listTaskChangeRequests = (params = {}) => http.get('/student-cases/tasks/change-requests', { params })
export const decideTaskChange = (reviewId, data) => http.post(`/student-cases/reviews/${reviewId}/decide`, data)
export const checkinCaseTask = (taskId, data) => http.post(`/student-cases/tasks/${taskId}/checkins`, data)
export const uploadCheckinAttachment = (checkinId, file) => {
  const formData = new FormData()
  formData.append('file', file)
  return http.post(`/student-cases/task-checkins/${checkinId}/attachments`, formData, {
    headers: { 'Content-Type': 'multipart/form-data' }
  })
}
export const listCheckinAttachments = (checkinId) => http.get(`/student-cases/task-checkins/${checkinId}/attachments`)
export const getTaskReminders = (params = {}) => http.get('/case-tasks/reminders', { params })
export const batchCheckinTasks = (data) => http.post('/case-tasks/batch-checkin', data)
export const listStageCompletions = (caseId) => http.get(`/student-cases/${caseId}/stage-completions`)
export const rebuildStageCompletion = (caseId) => http.post(`/student-cases/${caseId}/stage-completions/rebuild`)
export const getWeeklyPoints = (caseId) => http.get(`/student-cases/${caseId}/weekly-points`)
export const getMyCase = () => http.get('/student-cases/my-case')
export const listCaseVersions = (caseId) => http.get(`/student-cases/${caseId}/versions`)
