"""add student_knowledge_records

Revision ID: 00e2fdc191e0
Revises: d363eb9469eb
Create Date: 2026-08-12 10:07:05.055202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e2fdc191e0'
down_revision: Union[str, None] = 'd363eb9469eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_knowledge_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_knowledge_records_assignment_id'), 'student_knowledge_records', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_records_knowledge_point_id'), 'student_knowledge_records', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_records_student_id'), 'student_knowledge_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_knowledge_records_student_id'), table_name='student_knowledge_records')
    op.drop_index(op.f('ix_student_knowledge_records_knowledge_point_id'), table_name='student_knowledge_records')
    op.drop_index(op.f('ix_student_knowledge_records_assignment_id'), table_name='student_knowledge_records')
    op.drop_table('student_knowledge_records')
    # ### end Alembic commands ###
