"""add grading tables

Revision ID: 86e937410e61
Revises: f8adfaa7edf4
Create Date: 2026-08-12 09:15:59.460288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e937410e61'
down_revision: Union[str, None] = 'f8adfaa7edf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('prompt_type', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.String(length=4000), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grading_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_answer_id', sa.Integer(), nullable=False),
    sa.Column('grading_type', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_comment', sa.String(length=2000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_points', sa.JSON(), nullable=True),
    sa.Column('knowledge_points', sa.JSON(), nullable=True),
    sa.Column('raw_ai_result', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('teacher_score', sa.Float(), nullable=True),
    sa.Column('teacher_comment', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_answer_id'], ['submission_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_results_submission_answer_id'), 'grading_results', ['submission_answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grading_results_submission_answer_id'), table_name='grading_results')
    op.drop_table('grading_results')
    op.drop_table('grading_prompt_versions')
    # ### end Alembic commands ###
