"""add student_knowledge_stats

Revision ID: 8cede53c312e
Revises: 00e2fdc191e0
Create Date: 2026-08-12 14:03:44.953766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cede53c312e'
down_revision: Union[str, None] = '00e2fdc191e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_knowledge_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(length=16), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_point_id')
    )
    op.create_index(op.f('ix_student_knowledge_stats_knowledge_point_id'), 'student_knowledge_stats', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_stats_student_id'), 'student_knowledge_stats', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_knowledge_stats_student_id'), table_name='student_knowledge_stats')
    op.drop_index(op.f('ix_student_knowledge_stats_knowledge_point_id'), table_name='student_knowledge_stats')
    op.drop_table('student_knowledge_stats')
    # ### end Alembic commands ###
